
title = "Sergey Sova"
description = "Notes about development"
base_url = "https://sova.dev"
# theme = "after-dark"
theme = "hyde"
compile_sass = true

highlight_code = true
highlight_theme = "visual-studio-dark"

build_search_index = false
generate_rss = false
check_external_links = true

paginate_by = 10

default_language = "en"
languages = [
  { code = "ru", rss = false },
]

taxonomies = [
    # You can enable/disable RSS
    { name = "categories" },
    { name = "tags" },
]

[extra]
hyde_links = [
  { url = "https://github.com/sergeysova", name = "Github" },
  { url = "https://t.me/sergeysova", name = "Telegram" },
  { url = "https://twitter.com/_sergeysova", name = "Twitter" },
  # { url = "/ru", name = "По-русски" },
  { url = "https://podcast.sova.dev", name = "Подкаст" },
]
hyde_theme = "theme-base-0d"

after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "https://twitter.com/_sergeysova", name = "Twitter"},
    {url = "https://mastodon.social/@sergeysova", name = "Mastodon"},
    {url = "https://github.com/sergeysova", name = "Github"},
]
after_dark_title = "Sergey Sova"
